# Generated by Django 4.2.4 on 2023-08-10 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("post_id", models.UUIDField(blank=True, default=uuid.uuid4)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("json", models.JSONField(blank=True, default=dict)),
                (
                    "name",
                    models.CharField(blank=True, default=uuid.uuid4, max_length=255),
                ),
                ("is_active", models.BooleanField(blank=True, default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The person who created the survey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("submit_survey", "Can submit survey"),
                    ("survey_view_result", "Can view survey results"),
                ),
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveyjs.survey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The person who submitted the survey if submitted while logged in",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="upload/files/")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        help_text="The result which this attachment is originated to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveyjs.result",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The person who uploaded the document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
